feature_matcher: orb

num_features: 500

constant_motion: true

const_motion_weights_car: [50, 0.0015] # rot, trans

const_motion_weights_ped: [0.005, 0.0005]

keep_track_for_n_frames_after_lost: 11

sliding_window_ba: 15

ba_every_n_steps: 1

sliding_window_desc: 25

cluster_radius_car: 4

cluster_radius_ped: 2

max_dist: 55
ba_normalize_trans_error: true

min_landmarks_ped: 3
min_landmarks_car: 13

# available options for trust_2d: "yes" (only use trackr-cnn info),
#                                 "no" (do not use trackr-cnn at all),
#                                 "a bit" (use pipeline as outlined in thesis)
trust_2d: "a bit"

save_updated_2d_track: false
